services:
  - type: web
    name: skillvista
    runtime: node
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
